### ISSUE TITLE
Meter, vertical breaks in mobile view

### ISSUE THREAD

**Issue by tobias-flitsch** [HewlettPackard/grommet#39]
When using the `<Meter type={arc|circle} vertical={true}/>` component it is not displayed correctly in mobile device view, width ~330px. The value is not centered any more and the ledgend is messed up.

Can we include some conditional display of the ledgend, i.e. 
```css
@include media-query(palm) {
  .legend {
    display: none;
  }
}
```
or switch to the horizontal display mode if the width is too small.

**Comment by tobias-flitsch** [comment]
This actually helped in file _objects.meter.scss

```scss
 &--vertical {
    //...
    // Never display the ledgend in vertical mode
    @include media-query(palm) {
      .meter__legend {
        display: none;
      }
    }
  }
```
