### ISSUE TITLE
Meter .legend__item-value width causes line-break

### ISSUE THREAD

**Issue by tobias-flitsch** [HewlettPackard/grommet#40]
The css properties defined in _objects.legend.scss:

```scss
.legend {
  //...
  &__item, &__total {
    //...
    &-value {
      //...
      width: double($inuit-base-spacing-unit); // here in line 25
    }
  }
}
```

will cause the labels to do a line break if they are larger than 3 digits and if 2-character units are specified. Removing this property or doubling the value will remove the issue. 

Assuming that most values will be within 0-999 and most units being 2-characters, doubling the width should be fine.
